### PR TITLE
New service to calculate a route between two GeoPoints

### PR DESCRIPTION
**Pull request by atiderko**
Hi,

based on your open_street_map package I added the calculation of a route between two GeoPoints. In this context a new service was added to geographic_msgs, see https://github.com/ros-geographic-info/geographic_info/pull/7

I thought maybe that needs someone ...

Regards,
Alex

### CODE REVIEW

**Comment by bmagyar** [comment]
Alex, any interest in giving a go to this PR again? I know it's been some time but I'd like to prepare a release soon for Kinetic and Lunar

**Comment by atiderko** [comment]
@bmagyar thanks for the ping! It's some time since we worked with this package, but i'm interested in include this part of code. I or my college will see, how to resolve the conflicts of this pull request. But next week ;)

**Comment by bmagyar** [comment]
On Nov 17, 2017 11:50, "Alexander Tiderko" <notifications@github.com> wrote:

@bmagyar <https://github.com/bmagyar> thanks for the ping! It's some time
since we worked with this package, but i'm interested in include this part
of code. I or my college will see, how to resolve the conflicts of this
pull request. But next week ;)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ros-geographic-info/open_street_map/pull/1#issuecomment-345223717>,
or mute the thread

**Comment by bmagyar** [comment]
Perhaps it would be easier to cherry pick on a fresh checkout,  I see there
has been several "update to upstream"s that may give you their own
conflicts for no gain.

**Comment by dieg0-** [comment]
Hi @bmagyar, I've discussed this with my colleague @atiderko  and we are preparing a new pull request from a fresh fork. It addresses all the changes made on this PR and solves the conflicts. I will have it ready in a couple of days, and then if you'd like, this PR can be ignored so that you review the new one.

Cheers,
Diego

**Comment by bmagyar** [comment]
Great, thanks guys!

**Comment by bmagyar** [comment]
Closing in favour of #10

**Pull request closed without merging**
